/*
 * colorMap.h
 *
 * Created: 8/13/2013 9:50:46 AM
 *  Author: Michael
 *  Contains color look up tables generated by dividing the full HSL hue range
 *  in to steps, then converting each of these steps to the RGB system
 *  using processing. Saturation & Lightness values were fixed at 1.0 & 0.5 
 *  respectively. 
 *
 * DJTT - MIDI Fighter Twister - Embedded Software License
 * Copyright (c) 2016: DJ Tech Tools
 * Permission is hereby granted, free of charge, to any person owning or possessing 
 * a DJ Tech-Tools MIDI Fighter Twister Hardware Device to view and modify this source 
 * code for personal use. Person may not publish, distribute, sublicense, or sell 
 * the source code (modified or un-modified). Person may not use this source code 
 * or any diminutive works for commercial purposes. The permission to use this source 
 * code is also subject to the following conditions:
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,  FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */ 


#ifndef COLORMAP_H_
#define COLORMAP_H_

	#include <ASF.H>

	const uint8_t colorMap8[256][3];
	const uint8_t colorMap7[128][3];
	const uint8_t brightnessMap[128];
	const uint8_t animationBrightnessMap[32];

#endif /* COLORMAP_H_ */